name: Adventure Argentina
description: Guided explorations in Argentina and Great Britain
baseurl: ''
keywords: walking, mountain biking, cycling, mountains, jungle, Jujuy, Argentina, UK, Andes, rainforest

url: "https://adventureargentina.co.uk/"

plugins:
  - jekyll-sitemap

sass:
    sass_dir: ./_scss

include: ["_pages"]

permalink: /:title/
